[workspace]
resolver = "2"
members = [ "rust/acm", 
    "rust/ex02/fist01", "rust/ex02/fist02", "rust/ex02/fist03", "rust/ex02/fist04", "rust/ex02/fist05", "rust/ex02/fist06", "rust/ex02/fist07", "rust/ex03/f01",
]
